library(tinytest)
library(tinysnapshot)
using("tinysnapshot")
options("tinysnapshot_os" = "Linux")
if (Sys.info()["sysname"] != "Linux") exit_file("Linux snapshots")
options("tinysnapshot_device" = "svglite")
options("tinysnapshot_device_args" = list(user_fonts = fontquiver::font_families("Liberation")))
